package com.kurzdigital.idl;

import java.util.HashMap;

public enum IdlElement {
	VEHICLE_CLASS("DCA"),
	RESTRICTION_CODES("DCB"),
	ENDORSEMENT_CODES("DCD"),
	DATE_OF_EXPIRY("DBA"),
	CUSTOMER_FAMILY_NAME("DCS"),
	CUSTOMER_FIRST_NAME("DAC"),
	CUSTOMER_FIRST_NAME_ALT("DCT"),
	CUSTOMER_MIDDLE_NAME("DAD"),
	DATE_OF_ISSUE("DBD"),
	DATE_OF_BIRTH("DBB"),
	SEX("DBC"),
	EYE_COLOR("DAY"),
	BODY_HEIGHT("DAU"),
	ADDRESS_STREET("DAG"),
	ADDRESS_CITY("DAI"),
	ADDRESS_JURISDICTION_CODE("DAJ"),
	ADDRESS_POSTAL_CODE("DAK"),
	CUSTOMER_ID_NUMBER("DAQ"),
	DOCUMENT_DISCRIMINATOR("DCF"),
	COUNTRY("DCG"),
	FAMILY_NAME_TRUNCATION("DDE"),
	FIRST_NAME_TRUNCATION("DDF"),
	MIDDLE_NAME_TRUNCATION("DDG"),
	ADDRESS_STREET_2("DAH"),
	HAIR_COLOR("DAZ"),
	PLACE_OF_BIRTH("DCI"),
	AUDIT_INFORMATION("DCJ"),
	INVENTORY_CONTROL_NUMBER("DCK"),
	ALIAS_FAMILY_NAME("DBN"),
	ALIAS_GIVEN_NAME("DBG"),
	ALIAS_SUFFIX_NAME("DBS"),
	NAME_SUFFIX("DCU"),
	WEIGHT_RANGE("DCE"),
	ETHNICITY("DCL"),
	STANDARD_VEHICLE_CLASSIFICATION("DCM"),
	STANDARD_ENDORSEMENT_CODE("DCN"),
	STANDARD_RESTRICTION_CODE("DCO"),
	VEHICLE_CLASSIFICATION_DESCRIPTION("DCP"),
	ENDORSEMENT_CODE_DESCRIPTION("DCQ"),
	RESTRICTION_CODE_DESCRIPTION("DCR"),
	COMPLIANCE_TYPE("DDA"),
	CARD_REVISION_DATE("DDB"),
	HAZMAT_ENDORSEMENT_EXPIRATION_DATE("DDC"),
	LIMITED_DURATION_DOCUMENT_INDICATOR("DDD"),
	WEIGHT_POUNDS("DAW"),
	WEIGHT_KILOGRAMS("DAX"),
	UNDER_18_UNTIL_DATE("DDH"),
	UNDER_19_UNTIL_DATE("DDI"),
	UNDER_21_UNTIL_DATE("DDJ"),
	ORGAN_DONOR_INDICATOR("DDK"),
	VETERAN_INDICATOR("DDL");

	private String id;

	IdlElement(String id) {
		this.id = id;
	}

	public String getId() {
		return id;
	}

	public static IdlElement get(String id) {
		return id2element.get(id);
	}

	private static HashMap<String, IdlElement> id2element = new HashMap<>();
	static {
		for (IdlElement el : IdlElement.values()) {
			id2element.put(el.getId(), el);
		}
	}
}

